version: '3'
services:
  backend:
    build: .
    restart: unless-stopped
    container_name: admin-api
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - ${PORT}:3000
    volumes:
      - .:/app
    depends_on:
      - admin_db
    networks:
      - admin-network

  admin_db:
    image: postgres
    container_name: 'admin-db'
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - .pgdb:/var/lib/postgresql/data
    networks:
      - admin-network

# volumes:
#   node_modules:

networks:
  admin-network:
    driver: bridge